current:
  userId: '123456'

spring:
  datasource:
    druid:
      url: jdbc:mysql://121.4.32.77:3306/data_model
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 设置MyBatis-Plus的全局配置
  global-config:
    db-config:
      # 设置实体类所对应的表的统一前缀
      table-prefix: tb_
      # 设置统一的主键生成策略
      id-type: assign_id
    banner: off
  # 配置类型别名所对应的包
  type-aliases-package: com.eardh.model
  mapper-locations: "classpath*:/mybatis/mapper/**/*.xml"

logging:
  level:
    com.eardh: debug
